####

- id: primary-network-node
  type: group
  role: [primary-network-node]
  requires: [deploy_start, primary-controller, controller]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
    hosts, firewall, deploy_start, cluster, cluster-haproxy,
    openstack-haproxy-stats, network-node-task]
  parameters:
    strategy:
      type: one_by_one

- id: network-node
  type: group
  role: [network-node]
  requires: [deploy_start, primary-network-node]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
    hosts, firewall, deploy_start, cluster, cluster-haproxy,
    openstack-haproxy-stats, network-node-task]
  parameters:
    strategy:
      type: parallel

### Tasks
- id: network-hiera-override
  type: puppet
  groups: [primary-controller, controller, primary-network-node, network-node]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: "network_hiera_override.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 120

- id: network-node-task
  type: puppet
  groups: [primary-network-node, network-node]
  requires: [cluster, firewall, network-hiera-override]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-network/openstack-network-controller.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

